### ISSUE TITLE
weather mod deflector

### ISSUE THREAD

**Issue by GoddessTT** [ResqDiver1317/AC-SpecialSauce#1]
The weather mod deflector is not working to protect homes in game. Not sure if it is a setting or something else.

**Comment by ResqDiver1317** [comment]
Was it set to protect blocks or to kill storms?

**Comment by GoddessTT** [comment]
So the info on their wiki says you right click the deflector....(poor melly) and I put one down at her place, couldn't find your weather thing so I put one down and activated a storm....haha it blew her place down. I had her try to right click, then put her own down, nothing happens when you right click.

**Comment by GoddessTT** [comment]
OH and spar said it wasn't working also (prior to me coming on).

**Comment by GoddessTT** [comment]
Had to remove as the base deflector wasn't working to protect.
