### ISSUE TITLE
Biomes not right

### ISSUE THREAD

**Issue by GoddessTT** [ResqDiver1317/AC-SpecialSauce#3]
Biomes are not right. Also shouldn't twilight lake be only in Twilight Dimenson? Jade has it saved, but rtp'd into that biome. Or is it being brought in by another mod?

See the following:

The Twilight Lake is a biome added by the Twilight Forest mod. This biome is a fairly standard lake, though they tend to have small islands with Canopy Trees. Lake Border biomes are found surrounding them. This biome is only found in the Twilight Forest dimension.

**Comment by ResqDiver1317** [comment]
This should be resolved with the previous update.
