### ISSUE TITLE
Runic Dungeons crash client, not server, on entry.

### ISSUE THREAD

**Issue by Noctleigh** [ResqDiver1317/AC-SpecialSauce#6]
First players: Drug and Jade

Initial Replication:
1. Sign into Minecraft
2. Create Portal for Runic Dungeon.
3. Enter Portal.
4. Open door with gold key.
5. Boss spawn block did not spawn boss.
6. Boss block was right clicked.
7. Client crashed.

Repeat Replication:
1. Sign into Minecraft.
2. Attempt to enter Runic Dungeon.
3. Client crashed.

**Comment by Noctleigh** [comment]
Possible Fix: https://forum.feed-the-beast.com/threads/1-0-2-corrupts-world-runic-dungeons-guardian-noclassdeffounderror.65195/

**Comment by ResqDiver1317** [comment]
Resolved. issue was caused by a bug with the boss spawning in the mod. Turned off the boss's and reset the dimension.
